services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "Build udagram-api-user"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user bluerosecloud52/udagram-api-user:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push bluerosecloud52/udagram-api-user:latest